# **What is NumPy?**

**NumPy = Numerical Python**

<ul><li>A Python library to handle numbers efficiently.</li>

<li>Why it exists: Python lists are slow for big math operations. NumPy arrays are fast, memory-efficient, and support multi-dimensional operations.</li></ul>

In [ ]:
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(type(arr))


[1 2 3]
<class 'numpy.ndarray'>


# What is an Array?

An array = a container of numbers, can be 1D, 2D, 3D, etc.

**Arrays = input features, images, sequences, labels. Operations = preprocessing, normalization, reshaping, feature scaling.**

In [ ]:
# 1D array → a row of numbers
a = np.array([1,2,3])
print("1D array:", a)

1D array: [1 2 3]


In [ ]:
# 2D array → table of numbers
b = np.array([[1,2],[3,4]])
print("2D array:\n", b)

2D array:
 [[1 2]
 [3 4]]


In [ ]:
# 3D array → stack of tables
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("3D array:\n", c)

3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Numpy Operations


* Basic Math
* Element wise Operations
* Aggregate Operations
*  Reshaping
* Indexing & Slicing







In [ ]:
x = np.array([1,2,3,4])

# Basic math
print(x + 2)          # [3 4 5 6]
print(x * 3)          # [3 6 9 12]

[3 4 5 6]
[ 3  6  9 12]


In [ ]:

# Element-wise operations
y = np.array([10,20,30,40])
print(x + y)          # [11 22 33 44]
print(x * y)          # [10 40 90 160]



[11 22 33 44]
[ 10  40  90 160]


In [ ]:

# Aggregate operations
print(np.sum(x))      # 10
print(np.mean(x))     # 2.5
print(np.max(x))      # 4
print(np.min(x))      # 1


10
2.5
4
1


In [ ]:

# Reshape
z = np.arange(12)       # [0 1 2 ... 11]
print("\n",z)
print("\n")
print(z.reshape(3,4))   # 3 rows, 4 cols



 [ 0  1  2  3  4  5  6  7  8  9 10 11]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Indexing & slicing
print(x[0])             # first element
print(x[1:3])           # slice [2 3]

1
[2 3]


# What is a Vector?

A vector is a 1-dimensional array.

Example: [23, 70, 5.8] → Age, weight, height of a person

In [ ]:
vector = np.array([23, 70, 5.8])
print("Vector:", vector)
print("Shape:", vector.shape)  # (3,)

Vector: [23.  70.   5.8]
Shape: (3,)


# Intro to Pytorch

**What is a Tensor?**

A tensor = generalized array, can have any number of dimensions.

| Dimension | Example | Analogy | Shape |
|-----------|---------|---------|-------|
| 0D (scalar) | 5 | Single ball | () |
| 1D (vector) | [1,2,3] | Line of Lego blocks | (3,) |
| 2D (matrix) | [[1,2],[3,4]] | Tray of Lego blocks | (2,2) |
| 3D | [[[1,2],[3,4]], [[5,6],[7,8]]] | Stack of trays | (2,2,2) |
| 4D | Batch of 3D tensors | Multiple stacks | (batch, depth, rows, cols) |


*   All vectors and matrices are tensors, but tensors can be higher-dimensional.
*   In deep learning, every input/output is a tensor.



In [ ]:
import torch

# Single data point with 3 features → 1D tensor
x = torch.tensor([23,70,5.8])
print(x)
print(x.shape)


tensor([23.0000, 70.0000,  5.8000])
torch.Size([3])


In [ ]:
# Batch of 4 data points → 2D tensor
batch_x = torch.tensor([
    [23,70,5.8],
    [45,80,5.5],
    [30,65,5.7],
    [25,72,5.6]
])

print(batch_x)
print(batch_x.shape)

tensor([[23.0000, 70.0000,  5.8000],
        [45.0000, 80.0000,  5.5000],
        [30.0000, 65.0000,  5.7000],
        [25.0000, 72.0000,  5.6000]])
torch.Size([4, 3])


In [ ]:
# Random tensor for CNN image input → 4D (batch, channels, height, width)
images = torch.rand((32,3,224,224))
print(images)
print(images.shape)

tensor([[[[0.0649, 0.3987, 0.3551,  ..., 0.3225, 0.8471, 0.2675],
          [0.9924, 0.1370, 0.0915,  ..., 0.0518, 0.1545, 0.8687],
          [0.2059, 0.9748, 0.9905,  ..., 0.2071, 0.8924, 0.9256],
          ...,
          [0.7368, 0.1944, 0.5820,  ..., 0.1632, 0.4738, 0.8696],
          [0.4046, 0.1906, 0.8055,  ..., 0.1642, 0.4389, 0.6226],
          [0.9489, 0.7977, 0.4830,  ..., 0.2608, 0.8430, 0.9945]],

         [[0.6890, 0.8569, 0.5465,  ..., 0.3630, 0.0450, 0.5386],
          [0.7310, 0.7156, 0.9981,  ..., 0.7398, 0.0743, 0.7147],
          [0.6320, 0.9724, 0.4409,  ..., 0.5982, 0.8155, 0.3166],
          ...,
          [0.9741, 0.5655, 0.7661,  ..., 0.9826, 0.3576, 0.2590],
          [0.7586, 0.7317, 0.8844,  ..., 0.2435, 0.8513, 0.8084],
          [0.8827, 0.9646, 0.3907,  ..., 0.3728, 0.3685, 0.8711]],

         [[0.8778, 0.2068, 0.7353,  ..., 0.2468, 0.3063, 0.0234],
          [0.7577, 0.7991, 0.5069,  ..., 0.5522, 0.0103, 0.3252],
          [0.6900, 0.6910, 0.5578,  ..., 0

# Where do we use these?

| Tensor Type | Shape Example                           | Deep Learning Use  |
| ----------- | --------------------------------------- | ----------------- |
| 1D vector   | `(features,)`                           | Single data point |
| 2D matrix   | `(batch_size, features)`                | Input to MLP      |
| 3D tensor   | `(sequence, features, embedding)`       | RNN input         |
| 4D tensor   | `(batch_size, channels, height, width)` | CNN input (images)|
| 5D tensor   | `(batch_size, frames, channels, H, W)`  | Video input       |


In [ ]:
import torch

# From list
x = torch.tensor([1,2,3])

print(x)
print(type(x))

tensor([1, 2, 3])
<class 'torch.Tensor'>


In [ ]:
# Zeros, ones
zeros = torch.zeros((2,2))
print(zeros)

tensor([[0., 0.],
        [0., 0.]])


In [ ]:

ones = torch.ones((2,2))
print(ones)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:

# Random tensor
rand = torch.rand((2,3))
print(rand)


tensor([[0.4911, 0.1703, 0.7295],
        [0.3980, 0.7327, 0.1719]])


In [ ]:

# Shape
print(rand.shape)  # e.g., (2,3)


torch.Size([2, 3])


In [ ]:

# Element-wise operations
y = torch.tensor([4,5,6])
print(x + y)       # [5 7 9]


tensor([5, 7, 9])


In [ ]:

# Matrix multiplication
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
print(torch.matmul(a,b))

tensor([[19, 22],
        [43, 50]])
